language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly

matrix:
  allow_failures:
    - julia: nightly

sudo: required

git:
  depth: 9999

notifications:
  email: false

addons:
  apt_packages:
    - gfortran

branches:
  only:
    - master

before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:
  - julia --check-bounds=yes -e 'VERSION >= v"0.7" && using Pkg; Pkg.clone(pwd()); Pkg.build("NLPModelsJuMP"); Pkg.test("NLPModelsJuMP"; coverage=true)'

after_success:
  - julia -e 'VERSION >= v"0.7" && using Pkg; Pkg.add("Documenter"); Pkg.clone("https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl"); cd(Pkg.dir("NLPModelsJuMP")); include(joinpath("docs", "make.jl"))'
  - julia -e 'VERSION >= v"0.7" && using Pkg; cd(Pkg.dir("NLPModelsJuMP")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
